"""
This file contains dictionaries mapping Fitzpatrick labels (in the 114 class set) to the labels in
DermaMNIST.

This file was generated by ChatGPT, and the mappings were verified as follows:
- obvious mappings to non-dermatologists (i.e., same name, e.g. actinic keratosis -> actinic 
keratoses) were assumed accurate without need for further evaluation
- less obvious mappings were supported by references

The official definitions of the HAM10000 labels (which the DermaMNIST used) can be found here:
https://www.nature.com/articles/sdata2018161

Per this, the DermaMNIST is based on HAM10000:
https://www.nature.com/articles/s41597-022-01721-8
"""

# Target labels (your 7 train labels), e.g. exactly as used in your training set:
# "actinic keratoses and intraepithelial carcinoma"
# "basal cell carcinoma"
# "benign keratosis-like lesions"
# "dermatofibroma"
# "melanoma"
# "melanocytic nevi"
# "vascular lesions"

# 

STRICT_LABEL_MAP = {
    # --- actinic keratoses and intraepithelial carcinoma ---
    # obvious mapping
    "actinic keratosis": "actinic keratoses and intraepithelial carcinoma",

    # --- basal cell carcinoma ---
    # obvious mapping
    "basal cell carcinoma": "basal cell carcinoma",
    # HAM10000 lists cystic basal cell carcinoma as a subtype of basal cell carcinoma: https://www.nature.com/articles/sdata2018161
    "solid cystic basal cell carcinoma": "basal cell carcinoma",
    # a variant of basal cell carcinoma, per https://pubmed.ncbi.nlm.nih.gov/27043336/
    "basal cell carcinoma morpheiform": "basal cell carcinoma",

    # --- benign keratosis-like lesions ---
    # https://www.nature.com/articles/sdata2018161
    # ""Benign keratosis" is a generic class that includes seborrheic keratoses ..."
    "seborrheic keratosis": "benign keratosis-like lesions",

    # --- dermatofibroma ---
    # obvious mapping
    "dermatofibroma": "dermatofibroma",

    # --- melanoma ---
    # obviously the same
    "melanoma": "melanoma",
    # HAM10000 defines "melanoma" label as referring to "malignant" neoplasms: https://www.nature.com/articles/sdata2018161
    "malignant melanoma": "melanoma",
    # ssm is a subtype of melanoma, per: https://www.ncbi.nlm.nih.gov/sites/books/NBK459367/
    "superficial spreading melanoma ssm": "melanoma",
    # another subtype of melanoma, per https://www.ncbi.nlm.nih.gov/sites/books/NBK459367/
    "lentigo maligna": "melanoma",

    # --- melanocytic nevi ---
    # same thing, per https://link.springer.com/article/10.1007/s00521-024-09900-x
    "nevocytic nevus": "melanocytic nevi",
    # congenital nevus is a subtype of melanocytic nevi: https://www.ncbi.nlm.nih.gov/books/NBK563168/
    "congenital nevus": "melanocytic nevi",
    # halo nevi are a subtype of melanocytic nevi, per: https://jamanetwork.com/journals/jamadermatology/fullarticle/409966
    "halo nevus": "melanocytic nevi",

    # --- vascular lesions ---
    # HAM10000 definition lists "pyogenic granuloma" under its "vascular lesions" category: https://www.nature.com/articles/sdata2018161
    "pyogenic granuloma": "vascular lesions",
    # "granuloma Pyogenic" is a synonym for "pyogenic granuloma", per https://pmc.ncbi.nlm.nih.gov/articles/PMC3303528/
    # Why are the synonyms as different labels? The Fitzpatrick paper does not mention any label collapsing
    # for the 114 labels, so they likely just scraped whatever label was on the website. The original
    # websites have images labeled by many dermatologists, some of whom may have used different names.
    # Since these websites were created for training medical students, not for ML pipelines, the maintainers
    # of the original sites did not bother collapsing the labels either.
    "granuloma pyogenic": "vascular lesions",
    # a subtype, per https://www.childrenshospital.org/conditions-treatments/capillary-malformation
    "port wine stain": "vascular lesions",
    # a type of vascular lesion, per https://pmc.ncbi.nlm.nih.gov/articles/PMC7290907/
    "telangiectases": "vascular lesions",
}

# Optional / debatable mappings – use ONLY if you’re comfortable with them.
# Upon further research, these do not align with the HAM10000 definitions. DO NOT USE THEM, since
# our training data is based on HAM10000 labels.
OPTIONAL_LABEL_MAP = {
    # melanocytic nevi (borderline, but often grouped this way in practice)
    "becker nevus": "melanocytic nevi",

    # vascular lesions (malignant vascular tumor; include only if you define
    # vascular lesions purely by histologic type rather than benign/malignant)
    "kaposi sarcoma": "vascular lesions",
}

FULL_LABEL_MAP = {**STRICT_LABEL_MAP, **OPTIONAL_LABEL_MAP}

# Example usage:
# mapped_label = STRICT_LABEL_MAP.get(original_label)
# if mapped_label is None:
#     # label not mappable under strict scheme; drop or handle separately
#     pass
