from typing import Literal
import torch
from torchvision.models import resnet18, resnet50
from torchvision.models.resnet import ResNet18_Weights, ResNet50_Weights, BasicBlock, ResNet
import torch.nn as nn
import torch.nn.functional as F
from tqdm import tqdm
import numpy as np

import matplotlib.pyplot as plt
from sklearn.metrics import roc_auc_score

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
num_classes = 7
NUM_EPOCHS = 5

# AI Usage: attention mechanism suggestion and code to implement it was generated by AI.
class SEBlock(nn.Module):
    def __init__(self, channels, reduction=16):
        super().__init__()
        self.fc1 = nn.Linear(channels, channels // reduction)
        self.fc2 = nn.Linear(channels // reduction, channels)

    def forward(self, x):
        b, c, h, w = x.size()
        # Squeeze: global average pooling
        s = x.mean(dim=(2, 3))          # [B, C]
        # Excitation: small MLP
        z = F.relu(self.fc1(s), inplace=True)
        z = torch.sigmoid(self.fc2(z))  # [B, C]
        z = z.view(b, c, 1, 1)
        return x * z

class SEBasicBlock(BasicBlock):
    # keep the same expansion as BasicBlock
    expansion = BasicBlock.expansion

    def __init__(self,
                 inplanes,
                 planes,
                 stride=1,
                 downsample=None,
                 groups=1,
                 base_width=64,
                 dilation=1,
                 norm_layer=None,
                 reduction=16):
        super().__init__(inplanes, planes, stride, downsample,
                         groups, base_width, dilation, norm_layer)
        self.se = SEBlock(self.conv2.out_channels, reduction=reduction)

    def forward(self, x):
        identity = x

        out = self.conv1(x)
        out = self.bn1(out)
        out = self.relu(out)

        out = self.conv2(out)
        out = self.bn2(out)

        # SE attention
        out = self.se(out)

        if self.downsample is not None:
            identity = self.downsample(x)

        out += identity
        out = self.relu(out)

        return out
    
def se_resnet18(num_classes=7, weights=None):
    # block = SEBasicBlock instead of BasicBlock
    model = ResNet(
        block=SEBasicBlock,
        layers=[2, 2, 2, 2],
        num_classes=num_classes
    )

    if weights is not None:
        # Load standard ResNet18 weights, adapting where shapes match
        base = resnet18(weights=weights)
        state_dict = base.state_dict()

        # Remove classifier weights that don't match (1000 vs 7 classes)
        state_dict.pop("fc.weight", None)
        state_dict.pop("fc.bias", None)

        msg = model.load_state_dict(state_dict, strict=False)
        # conv/bn weights should load; SE layers will be randomly init

    return model

def create_resnet(
        size: Literal[18, 50],
        num_classes=num_classes,
        device=device,
        classifier=None,
        use_se: bool = False,
        se_reduction: int = 16,
    ):
    if size == 18:
        if use_se:
            # use ImageNet weights if desired; can start with None to train from scratch
            model = se_resnet18(num_classes=num_classes,
                                weights=ResNet18_Weights.IMAGENET1K_V1)
        else:
            model = resnet18(weights=ResNet18_Weights.IMAGENET1K_V1)
    elif size == 50:
        # You could later define SE for ResNet50 similarly
        model = resnet50(weights=ResNet50_Weights.IMAGENET1K_V1)
    else:
        raise ValueError(f"Unsupported ResNet size: {size}")

    if classifier is None:
        model.fc = nn.Linear(model.fc.in_features, num_classes)
    else:
        model.fc = classifier

    return model.to(device)

def run_epoch(model, loader, criterion, optimizer=None, device=device):
    if optimizer is None:
        model.eval()
        torch.set_grad_enabled(False)
    else:
        model.train()
        torch.set_grad_enabled(True)

    epoch_loss = 0.0
    correct = 0
    total = 0

    for images, labels in tqdm(loader):
        images = images.to(device)
        labels = labels.to(device).squeeze(1).long() # # [B,1] -> [B]

        if optimizer is not None:
            optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        if optimizer is not None:
            loss.backward()
            optimizer.step()

        epoch_loss += loss.item() * images.size(dim=0)
        pred_labels = outputs.argmax(dim=1)
        correct += (pred_labels == labels).sum().item()
        total += labels.size(0)

    
    avg_loss = epoch_loss / len(loader.dataset)
    avg_acc = correct / total if total > 0 else 0

    torch.set_grad_enabled(True)

    return avg_loss, avg_acc 

# AI Usage: This function was originally written by me, but was modified by ChatGPT to
# add the metrics per-class accuracy and per-class AUC, as well as macro AUC for each epoch
def train_model(model, train_loader, val_loader, optimizer, criterion,
                num_epochs=NUM_EPOCHS, num_classes=num_classes, device=device):
    train_history = {
        "train_loss": [],
        "train_acc": [],
        "val_loss": [],
        "val_acc": [],
        "val_macro_auc": [],
        "val_per_class_acc": [],   # list of np arrays
        "val_per_class_auc": [],   # list of np arrays
    }

    for epoch in range(num_epochs):
        # ---- training epoch (same as before) ----
        train_loss, train_acc = run_epoch(model, train_loader, criterion, optimizer, device)

        # ---- validation epoch with richer metrics ----
        val_metrics = evaluate_model(model, val_loader, criterion, num_classes, device)

        train_history["train_loss"].append(train_loss)
        train_history["train_acc"].append(train_acc)

        train_history["val_loss"].append(val_metrics["loss"])
        train_history["val_acc"].append(val_metrics["overall_acc"])
        train_history["val_macro_auc"].append(val_metrics["macro_auc"])
        train_history["val_per_class_acc"].append(val_metrics["per_class_acc"])
        train_history["val_per_class_auc"].append(val_metrics["per_class_auc"])

        print(
            f"Epoch {epoch} | "
            f"Train loss: {train_loss:.4f}, acc: {train_acc:.3f} | "
            f"Val loss: {val_metrics['loss']:.4f}, "
            f"acc: {val_metrics['overall_acc']:.3f}, "
            f"macro AUC: {val_metrics['macro_auc']:.3f}"
        )

    return train_history

def plot_train_hist(train_history, type: Literal["loss", "acc"]):
    train_col = f"train_{type}"
    val_col = f"val_{type}"

    epochs = range(1, len(train_history[train_col]) + 1)
    plt.figure()

    plt.plot(epochs, train_history[train_col], label="Train")
    plt.plot(epochs, train_history[val_col], label="Validation")

    plt.xlabel("Epoch")
    plt.ylabel(type.upper())
    plt.legend()
    plt.title(f"Training vs. Validation {type.upper()}")

    return plt

# AI Usage: The below functions were generated by ChatGPT to plot various metrics, such as validation
# macro AUC and per class accuracy and AUC
def plot_val_macro_auc(train_history):
    epochs = range(1, len(train_history["val_macro_auc"]) + 1)
    plt.figure()

    plt.plot(epochs, train_history["val_macro_auc"], label="Val Macro AUC")

    plt.xlabel("Epoch")
    plt.ylabel("Macro AUC")
    plt.title("Validation Macro AUC over Epochs")
    plt.grid(True)
    plt.legend()

    return plt

def plot_per_class_accuracy(train_history, class_names=None):
    # last epoch’s per-class accuracy
    per_class_acc = train_history["val_per_class_acc"][-1]  # np.array [num_classes]

    num_classes = len(per_class_acc)
    indices = np.arange(num_classes)

    plt.figure(figsize=(8, 4))
    plt.bar(indices, per_class_acc)

    if class_names is None:
        class_names = [str(i) for i in range(num_classes)]

    plt.xticks(indices, class_names, rotation=45, ha='right')
    plt.ylabel("Accuracy (Recall)")
    plt.title("Per-Class Validation Accuracy (Last Epoch)")
    plt.ylim(0, 1.0)
    plt.tight_layout()

    return plt

def plot_per_class_auc(train_history, class_names=None):
    per_class_auc = train_history["val_per_class_auc"][-1]  # np.array [num_classes]

    num_classes = len(per_class_auc)
    indices = np.arange(num_classes)

    plt.figure(figsize=(8, 4))
    plt.bar(indices, per_class_auc)

    if class_names is None:
        class_names = [str(i) for i in range(num_classes)]

    plt.xticks(indices, class_names, rotation=45, ha='right')
    plt.ylabel("AUC")
    plt.title("Per-Class Validation AUC (Last Epoch)")
    plt.ylim(0, 1.0)
    plt.tight_layout()

    return plt

# AI Usage: this function was generated by ChatGPT
# also, I asked the AI some questions about what certain parts of the code do, such as
# what model.eval() does (so I can understand it better)
def compute_auc(model, val_loader, device=device):
    model.eval()
    torch.set_grad_enabled(False)

    all_probs = []
    all_labels = []

    for images, labels in tqdm(val_loader):
        images = images.to(device)
        # labels are initially [B, 1] where B is batch size
        # squeeze to [B]
        labels = labels.to(device).squeeze(1).long()

        outputs = model(images)
        probs = torch.softmax(outputs, dim=1)

        all_probs.append(probs.detach().cpu().numpy())
        all_labels.append(labels.detach().cpu().numpy())

    all_probs = np.concatenate(all_probs, axis=0) # shape: [N, num_classes]
    all_labels = np.concatenate(all_labels, axis=0) # shape [N]

    # multi-class macro AUC, one-vs-rest
    auc = roc_auc_score(
        all_labels,
        all_probs,
        multi_class="ovr",
        average="macro"
    )

    torch.set_grad_enabled(True)
    return float(auc)

# AI Usage: This function was generated by ChatGPT to look at per-class accuracy and AUC
def evaluate_model(model, loader, criterion, num_classes, device=device):
    model.eval()
    torch.set_grad_enabled(False)

    epoch_loss = 0.0
    correct = 0
    total = 0

    all_labels = []
    all_preds = []
    all_probs = []

    for images, labels in tqdm(loader):
        images = images.to(device)
        labels = labels.to(device).squeeze(1).long()  # [B,1] -> [B]

        with torch.no_grad():
            outputs = model(images)
            loss = criterion(outputs, labels)
            probs = torch.softmax(outputs, dim=1)

        # loss / accuracy aggregates
        batch_size = images.size(0)
        epoch_loss += loss.item() * batch_size

        pred_labels = outputs.argmax(dim=1)
        correct += (pred_labels == labels).sum().item()
        total += batch_size

        # store for per-class metrics & AUC
        all_labels.append(labels.cpu().numpy())
        all_preds.append(pred_labels.cpu().numpy())
        all_probs.append(probs.cpu().numpy())

    avg_loss = epoch_loss / len(loader.dataset)
    overall_acc = correct / total if total > 0 else 0.0

    # concat all batches
    all_labels = np.concatenate(all_labels, axis=0)   # [N]
    all_preds = np.concatenate(all_preds, axis=0)     # [N]
    all_probs = np.concatenate(all_probs, axis=0)     # [N, num_classes]

    # ---------- per-class accuracy (recall) ----------
    # acc_c = (# samples of class c predicted correctly) / (# samples of class c)
    per_class_acc = np.zeros(num_classes, dtype=np.float64)
    for c in range(num_classes):
        mask = (all_labels == c)
        if mask.sum() == 0:
            per_class_acc[c] = np.nan  # no samples of this class
        else:
            per_class_acc[c] = (all_preds[mask] == c).mean()

    # ---------- AUCs ----------
    # macro AUC (same as your compute_auc)
    macro_auc = roc_auc_score(
        all_labels,
        all_probs,
        multi_class="ovr",
        average="macro"
    )

    # per-class AUCs (one-vs-rest)
    per_class_auc = roc_auc_score(
        all_labels,
        all_probs,
        multi_class="ovr",
        average=None
    )  # shape: [num_classes]

    torch.set_grad_enabled(True)

    metrics = {
        "loss": float(avg_loss),
        "overall_acc": float(overall_acc),
        "macro_auc": float(macro_auc),
        "per_class_acc": per_class_acc,   # numpy array length = num_classes
        "per_class_auc": per_class_auc,   # numpy array length = num_classes
    }
    return metrics
